name: type checking

on:
  pull_request:
    paths:
      - inheritance_explorer/**/*.py
      - pyproject.toml
      - requirements/typecheck.txt
      - .github/workflows/type-checking.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: type check
    timeout-minutes: 60

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # run with oldest supported python version
        # so that we always get compatible versions of
        # core dependencies at type-check time
        python-version: '3.10'

    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements/typecheck.txt

    - name: list installed deps
      run: python -m pip list

    - name: Run mypy
      run: mypy inheritance_explorer
